---
title: "All_Species_Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    horizontal_layout: fill
    
    runtime: shiny
---

```{r setup, include=FALSE}
require(tidyverse)
require(data.table)
require(shiny)
require(here)
require(sp)
require(rgdal)
require(leaflet)
require(leafem)
require(leaflet.extras)
require(flexdashboard)
require(inborutils)

if("trias" %in% rownames(installed.packages()) == FALSE) {
  devtools::install_github("trias-project/trias")}

require(trias)

bioregions <- c("Atlantic", "Continental")
ts <- c("t0", "t1")
batches <- c("Batch1", "Batch2", "Batch3")
```

```{r create basemap, include=FALSE}
crs_wgs <- CRS("+proj=longlat +datum=WGS84 +no_defs ")
crs_bel <- CRS("+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs ")

bel_borders <- readOGR(here("./Data/Spatial"), "Belgie", stringsAsFactors = FALSE)
proj4string(bel_borders) <- crs_bel

bioreg_bel_clip <- readOGR(here("./Data/Spatial"), "bioreg_bel_clip", stringsAsFactors = FALSE)

grid_pal <- colorFactor(palette = c("red", "black"), domain = utm_polygons$grid, levels = c("utm1", "utm5"))
bioreg_pal <- colorFactor(palette = c("darkgrey", "white"), domain = bioreg_bel_clip$BIOGEO, levels = c("Continental", "Atlantic"))

basemap <- leaflet(bioreg_bel_clip) %>% 
  addTiles() %>% 
  addPolygons(fillColor = ~bioreg_pal(BIOGEO),
              fillOpacity = 0.5,
              stroke = FALSE) %>% 
  addPolylines(data = spTransform(bel_borders, crs_wgs),
               color = "black",
               opacity = 1,
               weight = 2) %>% 
  addScaleBar(position = "bottomleft") %>% 
  addLogo(img = "https://cdn2.iconfinder.com/data/icons/map-and-navigation-12/48/57-512.png", src = "remote", position = "bottomright") %>% 
  setMapWidgetStyle(list(background= "white"))
```

```{r get & merge utm_polygons, include=FALSE}
utm_merged <- data.frame()

for(t in ts){
  for(b in batches){
    fn <- paste0("./Data/Spatial/" , t, "_manageability_utmpolygons_", b, ".shp")
    fn2 <- paste0( t, "_manageability_utmpolygons_", b)
    if(file.exists(here(fn))){
      temp_utm <- readOGR(here("./Data/Spatial"), fn2, stringsAsFactors = FALSE)
      temp_utm$tx <- t
      if(class(utm_merged) == "SpatialPolygonsDataFrame"){
        utm_merged <- rbind.SpatialPolygonsDataFrame(utm_merged, temp_utm)
      }else{
        utm_merged <- temp_utm
      }
    }else{
      next()
    }
  }
}

```

```{r get & merge GridStats, include= FALSE}
stats_merged <- data.frame()

for(t in ts){
  for(b in batches){
    fn <- paste0("./Data/Input/" , t, "_manageability_GridStats_", b, ".csv")
    if(file.exists(here(fn))){
      temp_stats <- read_delim(here(fn), delim = ";")
        temp_stats$tx <- t
      if(nrow(stats_merged) > 0){
        stats_merged <- rbind.SpatialPolygonsDataFrame(stats_merged, temp_stats)
      }else{
        stats_merged <- temp_stats
      }
    }else{
      next()
    }
  }
}
```

```{r create choiceslist, include=FALSE}
spec_ind <- read_delim("https://raw.githubusercontent.com/inbo/IAS_Species_Dashboard/master/Data/Lists/nameserver_species_identifiers_for_t0.csv", 
                       ";", escape_double = FALSE, col_types = cols(t0_from = col_date(format = "%d/%m/%Y"), 
                                                                    t0_to = col_date(format = "%d/%m/%Y"), 
                                                                    t1_from = col_date(format = "%d/%m/%Y"), 
                                                                    t1_to = col_date(format = "%d/%m/%Y")), 
                       trim_ws = TRUE)

species_choices <- spec_ind %>% 
  filter(!is.na(Batch)) %>% 
  mutate(Species = case_when(grepl("Salvinia", gbifapi_acceptedScientificName) ~ "Salvinia auriculata Aubl.",
                             TRUE ~ gbifapi_acceptedScientificName)) %>% 
  distinct(Species) 

species_choices$Species <- str_sort(species_choices$Species)

spec_ind <- spec_ind %>% 
  filter(!is.na(Batch))
```

```{r setup TrIAS data, include=FALSE}
df_ts <- read_tsv(here("Data",
                    "Input",
                    "df_timeseries.tsv"))

df_ts_compact <-
  df_ts %>%
  group_by(taxonKey, year, classKey) %>%
  summarise(
    obs = sum(obs),
    cobs = sum(cobs),
    ncells = sum(pa_cobs),
    c_ncells = sum(pa_cobs)
  ) %>%
  ungroup()
```

Sidebar {.sidebar}
==================================
Select a species from the dropdown

```{r echo=FALSE}
selectInput(inputId = "species", label = "Species dropdown", choices = species_choices, selected = species_choices[1], multiple = FALSE, selectize = FALSE)
```

```{r}
renderText({print("")})
renderText({
  spec_ind_sub <- spec_ind %>% 
    filter(gbifapi_acceptedScientificName == input$species) %>% 
    distinct(gbifapi_acceptedKey, Batch, t0_from, t0_to)
  
  if(spec_ind_sub$Batch == 1){
    batch <- paste0(spec_ind_sub$Batch, "st")
  }
  if(spec_ind_sub$Batch == 2){
    batch <- paste0(spec_ind_sub$Batch, "nd")
  }
  if(spec_ind_sub$Batch == 3){
    batch <- paste0(spec_ind_sub$Batch, "rd")
  }
  if(spec_ind_sub$Batch > 3 ){
    batch <- paste0(spec_ind_sub$Batch, "th")
  }
  
  text_general <- paste0(input$species, " was included into the European list with the ", batch, " batch on ",  spec_ind_sub$t0_to, ".") 
  print(text_general)
})
renderText({print("")})
```

```{r}
renderText({print("placeholder gam about")})
```

```{r include=FALSE}
maxjaar <- lubridate::year(Sys.Date())
```


```{r echo=FALSE}
sliderInput(inputId = "evaluation_years", label = "evaluation period", min = 2000, max = maxjaar, value = c(2016,2018), step = 1, sep = "", dragRange = TRUE)
```

T0 - Baseline
==========================================

Row {data-height=50}
----------------------------------

```{r echo=FALSE}
renderText({
  spec_ind_sub <- spec_ind %>% 
    filter(gbifapi_acceptedScientificName == input$species) %>% 
    distinct(gbifapi_acceptedKey, Batch, t0_from, t0_to)
  
  text_t0 <- paste0("The graphs, tables and maps below contain observations from ", spec_ind_sub$t0_from, " to ",  spec_ind_sub$t0_to,".") 
  print(text_t0)
  
})
```

Row {data-height=400}
----------------------------------

```{r}
renderLeaflet({
  utm_t0 <- subset(utm_merged, utm_merged$tx == "t0")
  spec_ind_sub <- spec_ind %>% 
    filter(gbifapi_acceptedScientificName == input$species) %>% 
    distinct(gbifapi_acceptedKey, Batch, t0_from, t0_to)
  if(!is.na(spec_ind_sub$t0_from)){
    utm_spec <- subset(utm_t0, utm_t0$species == input$species)
    
    t0_map <- basemap %>% 
      addPolygons(data = utm_spec,
                  color = ~grid_pal(grid),
                  fill = FALSE,
                  opacity = 1,
                  weight = 1) %>% 
      addLegend(data = utm_spec,
                pal = grid_pal, 
                values = ~grid,
                position = "topright",
                title = "legenda")
    
    print(t0_map)
  }
})
```

Row {data-height=300}
----------------------------------

### Stats

*SAC: Special Areas of Conservation comprise of areas determined under the Habitat Directive

```{r}
renderTable({
  spec_stats <- stats_merged %>% 
    filter(gbfp_SN == input$species & tx == "t0") %>% 
    select(-tx)
  
  bioregion_test <- spec_stats %>% 
    filter(bioregion %in% bioregions) 
  
  if(nrow(bioregion_test) < 2){
    if(nrow(bioregion_test) > 0){
      missing_bioreg <- subset(bioregions, !grepl(pattern = bioregion_test$bioregion, bioregions))
      spec_stats <- spec_stats %>% 
        ungroup() %>% 
        add_row(gbfp_SN = input$species, bioregion = missing_bioreg, utm1 = NA, utm2 = NA, utm5 = NA, utm10 = NA, sac_perc = NA)
    }else{
      for(bio in bioregions){
        spec_stats <- spec_stats %>% 
        ungroup() %>% 
        add_row(gbfp_SN = input$species, bioregion = bio, utm1 = NA, utm2 = NA, utm5 = NA, utm10 = NA, sac_perc = NA)
      }
    }
  }
  
  temp_stats_3 <- spec_stats  %>% 
    ungroup() %>% 
    filter(!is.na(bioregion)) %>% 
    select(-gbfp_SN) %>% 
    rename(`UTM 1x1km` = utm1,
           `UTM 2x2km` = utm2,
           `UTM 5x5km` = utm5,
           `UTM 10x10km` = utm10,
           `% UTM 1x1km squares with SACs*` = sac_perc) %>% 
    t()
  
  colnames(temp_stats_3) <- temp_stats_3[1,]
  temp_stats_3 <- temp_stats_3[-1,]
  temp_stats_3 <- as.data.frame(temp_stats_3) %>% 
    rownames_to_column(var = "grid") 
  print(temp_stats_3)
})
```



T1 - Report
==================================

Row {data-height=50}
----------------------------------

```{r eval=TRUE}
renderText({
  spec_ind_sub <- spec_ind %>% 
    filter(gbifapi_acceptedScientificName == input$species) %>% 
    distinct(gbifapi_acceptedKey, Batch, t1_from, t1_to)
  if(!is.na(spec_ind_sub$t1_from)){
    text_t1 <- paste0("The graphs, tables and maps below contain observations from ", spec_ind_sub$t1_from, " to ",  spec_ind_sub$t1_to,".") 
    print(text_t1)
  }else{
    text_t1_alt <- paste0(input$species, " hasn't been the subject of a t1 reporting cycle")
    print(text_t1_alt)
  }
})
```

Row {data-height=650}
----------------------------------

```{r}
renderLeaflet({
  utm_t1 <- subset(utm_merged, utm_merged$tx == "t1")
  spec_ind_sub <- spec_ind %>% 
    filter(gbifapi_acceptedScientificName == input$species) %>% 
    distinct(gbifapi_acceptedKey, Batch, t1_from, t1_to)
  if(!is.na(spec_ind_sub$t1_from)){
    utm_spec <- subset(utm_t1, utm_t1$species == input$species)
    
    t1_map <- basemap %>% 
      addPolygons(data = utm_spec,
                  color = ~grid_pal(grid),
                  fill = FALSE,
                  opacity = 1,
                  weight = 1) %>% 
      addLegend(data = utm_spec,
                pal = grid_pal, 
                values = ~grid,
                position = "topright",
                title = "legenda")
    
    print(t1_map)
  }
})
```

Row {data-height=350}
----------------------------------

### Stats 

*SAC: Special Areas of Conservation comprise of areas determined under the Habitat Directive

```{r}
renderTable({
  spec_stats <- stats_merged %>% 
    filter(gbfp_SN == input$species & tx == "t1") %>% 
    select(-tx)
  
  bioregion_test <- spec_stats %>% 
    filter(bioregion %in% bioregions) 
  
  if(nrow(bioregion_test) < 2){
    if(nrow(bioregion_test) > 0){
      missing_bioreg <- subset(bioregions, !grepl(pattern = bioregion_test$bioregion, bioregions))
      spec_stats <- spec_stats %>% 
        ungroup() %>% 
        add_row(gbfp_SN = input$species, bioregion = missing_bioreg, utm1 = NA, utm2 = NA, utm5 = NA, utm10 = NA, sac_perc = NA)
    }else{
      for(bio in bioregions){
        spec_stats <- spec_stats %>% 
        ungroup() %>% 
        add_row(gbfp_SN = input$species, bioregion = bio, utm1 = NA, utm2 = NA, utm5 = NA, utm10 = NA, sac_perc = NA)
      }
    }
  }
  
  temp_stats_3 <- spec_stats  %>% 
    ungroup() %>% 
    filter(!is.na(bioregion)) %>% 
    select(-gbfp_SN) %>% 
    rename(`UTM 1x1km` = utm1,
           `UTM 2x2km` = utm2,
           `UTM 5x5km` = utm5,
           `UTM 10x10km` = utm10,
           `% UTM 1x1km squares with SACs*` = sac_perc) %>% 
    t()
  
  colnames(temp_stats_3) <- temp_stats_3[1,]
  temp_stats_3 <- temp_stats_3[-1,]
  temp_stats_3 <- as.data.frame(temp_stats_3) %>% 
    rownames_to_column(var = "grid") 
  print(temp_stats_3)
})
```

TrIAS Grafieken 
==========================================

```{r }
renderPrint({
  evaluation_years <- input$evaluation_years
  print(evaluation_years)
  })
```


```{r}
renderText({print("placeholder trias-link")})
```

Row {data-height=50}
----------------------------------

### Occupancy

```{r}

```

### Occupancy Corrected

Row {data-height=50}
----------------------------------

### Observations

### Observations corrected

```{r}
renderPrint({
  
  
  
  spec_ind_sub <- spec_ind %>% 
    filter(gbifapi_acceptedScientificName == input$species)
  
  df_key <- df_ts_compact %>% 
    filter(taxonKey %in% spec_ind_sub$gbifapi_acceptedKey)
  
  gam_occupancy <- apply_gam(
    df = df_key,
    y_var = "obs",
    eval_years = input$evaluation_years,
    type_indicator = "observations",
    baseline_var = "cobs",
    verbose = TRUE,
    saveplot = FALSE
  )
  
  print(gam_occupancy)
  
})
```

About
==========================================